# Connect to multiple containers
# https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers

services:
  airi-factorio:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    network_mode: host
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspace:cached
    entrypoint: /bin/bash
    command: ["-c", "trap : TERM INT; sleep infinity & wait"]
  rcon-api:
    image: ghcr.io/nekomeowww/factorio-rcon-api:2.0.5
    network_mode: host
    environment:
      FACTORIO_RCON_HOST: localhost
      FACTORIO_RCON_PORT: 27015
      FACTORIO_RCON_PASSWORD: 123456
    restart: always
